os: osx
language: generic
osx_image: xcode10.1
before_script:
- git clone https://github.com/flutter/flutter.git -b beta
- export PATH=$PATH:`pwd`/flutter/bin
script:
- flutter doctor
- flutter packages get
- flutter test
deploy:
  provider: script
  script:
  - flutter test
  on:
    tags: true
cache:
  directories:
  - "$HOME/.pub-cache"
notifications:
  slack:
    secure: d+tH9rHBY3ckKHqLh0ZdaueJEoCluvqFFo+wDxTJzRWQ61I8p1wLEYTZqZhi3uVpkFZO3uISiho/fTeqHL1DqU08vew3K8ob6gVDhwP3rRf+2fFORkN3akCX3+MKyZ0977QQ0afwF1hbJCKKqCzGToiv1B5pdSQUwGmO5B+OSD8jsdx7b2NZEDU3OTU+iwWpqMdS8rxvvwlFQk1IeZJ12+ymrwlvzAK+rDh4p5RnrHY8N4Wy8i/WGee9akU22v+LlanA6ydTA5/zxAG5QobMkIHPVCpVmhwYwGxeb/9L9M92BdzX7Hwd6F7ZbPr0cuaQDduG40fNjHCiym22DpDo75uNZr63bwb4bDJp+NbAbRopzH++s9GfdECNnBDFP/UCnTn7DbnEgi4rpZqWWBkcB82rLkMJpMV+7sMwForMlX9PE7FJUkjFze/9bj/EGbjTh74TbmAYUdlqSeg2LOOsqlKZszNrnkQHct+y453zZeNEPFMvYBBvpnWnqSJDfo6/eo291w41ouXB9zDR0NLIeRPlEP3AvUSBdAWUsQUWxASXF5ss+1UnQN+z9rIoqKmb0eU8WrBvNIvf7jEH/H1YLW2ddEdpC52vuGlATQrZy78pE46G3h4C315hFKRG/YYos4wkR5rhqPcOwtAdPlDdEZcSUResH8UZuwWv2sPW6MQ=
